// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fill_forward
DataFrame fill_forward(DataFrame df, CharacterVector column_names);
RcppExport SEXP _fasterr_fill_forward(SEXP dfSEXP, SEXP column_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type column_names(column_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_forward(df, column_names));
    return rcpp_result_gen;
END_RCPP
}
// full_seq
NumericVector full_seq(NumericVector x, double step);
RcppExport SEXP _fasterr_full_seq(SEXP xSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(full_seq(x, step));
    return rcpp_result_gen;
END_RCPP
}
// index_rows_na
LogicalVector index_rows_na(DataFrame df);
RcppExport SEXP _fasterr_index_rows_na(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(index_rows_na(df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fasterr_fill_forward", (DL_FUNC) &_fasterr_fill_forward, 2},
    {"_fasterr_full_seq", (DL_FUNC) &_fasterr_full_seq, 2},
    {"_fasterr_index_rows_na", (DL_FUNC) &_fasterr_index_rows_na, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fasterr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
