# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

index_rows_na <- function(df) {
    .Call(`_fasterr_index_rows_na`, df)
}

